// Code generated by protoc-gen-go.
// source: global.proto
// DO NOT EDIT!

/*
Package x is a generated protocol buffer package.

It is generated from these files:
	global.proto

It has these top-level messages:
	PB_UserWithMe
	PB_Message
	PB_Respons
	PB_Request
	PB_RequestMsgAddMany
	PB_ResponsMsgAddMany
	PB_RequestMsgAddOne
	PB_ResponsMsgAddOne
	PB_PushMsgAddMany
	PB_ResultMsgAddMany
*/
package x

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_UserWithMe struct {
	UserId         int32  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	UserName       string `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	FirstName      string `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName       string `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	About          string `protobuf:"bytes,5,opt,name=About" json:"About,omitempty"`
	FullName       string `protobuf:"bytes,6,opt,name=FullName" json:"FullName,omitempty"`
	AvatarUrl      string `protobuf:"bytes,7,opt,name=AvatarUrl" json:"AvatarUrl,omitempty"`
	PrivacyProfile int32  `protobuf:"varint,8,opt,name=PrivacyProfile" json:"PrivacyProfile,omitempty"`
	Phone          string `protobuf:"bytes,9,opt,name=Phone" json:"Phone,omitempty"`
	UpdatedTime    int32  `protobuf:"varint,10,opt,name=UpdatedTime" json:"UpdatedTime,omitempty"`
	AppVersion     int32  `protobuf:"varint,11,opt,name=AppVersion" json:"AppVersion,omitempty"`
}

func (m *PB_UserWithMe) Reset()                    { *m = PB_UserWithMe{} }
func (m *PB_UserWithMe) String() string            { return proto.CompactTextString(m) }
func (*PB_UserWithMe) ProtoMessage()               {}
func (*PB_UserWithMe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PB_UserWithMe) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_UserWithMe) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PB_UserWithMe) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PB_UserWithMe) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PB_UserWithMe) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *PB_UserWithMe) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *PB_UserWithMe) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *PB_UserWithMe) GetPrivacyProfile() int32 {
	if m != nil {
		return m.PrivacyProfile
	}
	return 0
}

func (m *PB_UserWithMe) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PB_UserWithMe) GetUpdatedTime() int32 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

func (m *PB_UserWithMe) GetAppVersion() int32 {
	if m != nil {
		return m.AppVersion
	}
	return 0
}

type PB_Message struct {
	MessageKey         string `protobuf:"bytes,1,opt,name=MessageKey" json:"MessageKey,omitempty"`
	RoomKey            string `protobuf:"bytes,2,opt,name=RoomKey" json:"RoomKey,omitempty"`
	UserId             int64  `protobuf:"varint,3,opt,name=UserId" json:"UserId,omitempty"`
	RoomTypeId         int32  `protobuf:"varint,4,opt,name=RoomTypeId" json:"RoomTypeId,omitempty"`
	MessageTypeId      int32  `protobuf:"varint,5,opt,name=MessageTypeId" json:"MessageTypeId,omitempty"`
	Text               string `protobuf:"bytes,6,opt,name=Text" json:"Text,omitempty"`
	ExtraJson          string `protobuf:"bytes,7,opt,name=ExtraJson" json:"ExtraJson,omitempty"`
	IsByMe             int32  `protobuf:"varint,8,opt,name=IsByMe" json:"IsByMe,omitempty"`
	IsStared           int32  `protobuf:"varint,9,opt,name=IsStared" json:"IsStared,omitempty"`
	CreatedMs          int64  `protobuf:"varint,10,opt,name=CreatedMs" json:"CreatedMs,omitempty"`
	CreatedDeviceMs    int64  `protobuf:"varint,11,opt,name=CreatedDeviceMs" json:"CreatedDeviceMs,omitempty"`
	SortId             int64  `protobuf:"varint,12,opt,name=SortId" json:"SortId,omitempty"`
	PeerSeenTime       int64  `protobuf:"varint,13,opt,name=PeerSeenTime" json:"PeerSeenTime,omitempty"`
	ServerReceivedTime int64  `protobuf:"varint,14,opt,name=ServerReceivedTime" json:"ServerReceivedTime,omitempty"`
	ServerDeletedTime  int64  `protobuf:"varint,15,opt,name=ServerDeletedTime" json:"ServerDeletedTime,omitempty"`
	ISeenTime          int64  `protobuf:"varint,16,opt,name=ISeenTime" json:"ISeenTime,omitempty"`
	ToPush             int32  `protobuf:"varint,17,opt,name=ToPush" json:"ToPush,omitempty"`
	MsgFile_LocalSrc   string `protobuf:"bytes,18,opt,name=MsgFile_LocalSrc,json=MsgFileLocalSrc" json:"MsgFile_LocalSrc,omitempty"`
	MsgFile_Status     int32  `protobuf:"varint,19,opt,name=MsgFile_Status,json=MsgFileStatus" json:"MsgFile_Status,omitempty"`
}

func (m *PB_Message) Reset()                    { *m = PB_Message{} }
func (m *PB_Message) String() string            { return proto.CompactTextString(m) }
func (*PB_Message) ProtoMessage()               {}
func (*PB_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PB_Message) GetMessageKey() string {
	if m != nil {
		return m.MessageKey
	}
	return ""
}

func (m *PB_Message) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *PB_Message) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_Message) GetRoomTypeId() int32 {
	if m != nil {
		return m.RoomTypeId
	}
	return 0
}

func (m *PB_Message) GetMessageTypeId() int32 {
	if m != nil {
		return m.MessageTypeId
	}
	return 0
}

func (m *PB_Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_Message) GetExtraJson() string {
	if m != nil {
		return m.ExtraJson
	}
	return ""
}

func (m *PB_Message) GetIsByMe() int32 {
	if m != nil {
		return m.IsByMe
	}
	return 0
}

func (m *PB_Message) GetIsStared() int32 {
	if m != nil {
		return m.IsStared
	}
	return 0
}

func (m *PB_Message) GetCreatedMs() int64 {
	if m != nil {
		return m.CreatedMs
	}
	return 0
}

func (m *PB_Message) GetCreatedDeviceMs() int64 {
	if m != nil {
		return m.CreatedDeviceMs
	}
	return 0
}

func (m *PB_Message) GetSortId() int64 {
	if m != nil {
		return m.SortId
	}
	return 0
}

func (m *PB_Message) GetPeerSeenTime() int64 {
	if m != nil {
		return m.PeerSeenTime
	}
	return 0
}

func (m *PB_Message) GetServerReceivedTime() int64 {
	if m != nil {
		return m.ServerReceivedTime
	}
	return 0
}

func (m *PB_Message) GetServerDeletedTime() int64 {
	if m != nil {
		return m.ServerDeletedTime
	}
	return 0
}

func (m *PB_Message) GetISeenTime() int64 {
	if m != nil {
		return m.ISeenTime
	}
	return 0
}

func (m *PB_Message) GetToPush() int32 {
	if m != nil {
		return m.ToPush
	}
	return 0
}

func (m *PB_Message) GetMsgFile_LocalSrc() string {
	if m != nil {
		return m.MsgFile_LocalSrc
	}
	return ""
}

func (m *PB_Message) GetMsgFile_Status() int32 {
	if m != nil {
		return m.MsgFile_Status
	}
	return 0
}

type PB_Respons struct {
	Status int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *PB_Respons) Reset()                    { *m = PB_Respons{} }
func (m *PB_Respons) String() string            { return proto.CompactTextString(m) }
func (*PB_Respons) ProtoMessage()               {}
func (*PB_Respons) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PB_Respons) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PB_Request struct {
	Status int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *PB_Request) Reset()                    { *m = PB_Request{} }
func (m *PB_Request) String() string            { return proto.CompactTextString(m) }
func (*PB_Request) ProtoMessage()               {}
func (*PB_Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PB_Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PB_RequestMsgAddMany struct {
	Messages []*PB_Message    `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
	Users    []*PB_UserWithMe `protobuf:"bytes,2,rep,name=Users" json:"Users,omitempty"`
}

func (m *PB_RequestMsgAddMany) Reset()                    { *m = PB_RequestMsgAddMany{} }
func (m *PB_RequestMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_RequestMsgAddMany) ProtoMessage()               {}
func (*PB_RequestMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PB_RequestMsgAddMany) GetMessages() []*PB_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PB_RequestMsgAddMany) GetUsers() []*PB_UserWithMe {
	if m != nil {
		return m.Users
	}
	return nil
}

type PB_ResponsMsgAddMany struct {
	Respons *PB_Respons `protobuf:"bytes,1,opt,name=Respons" json:"Respons,omitempty"`
}

func (m *PB_ResponsMsgAddMany) Reset()                    { *m = PB_ResponsMsgAddMany{} }
func (m *PB_ResponsMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_ResponsMsgAddMany) ProtoMessage()               {}
func (*PB_ResponsMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PB_ResponsMsgAddMany) GetRespons() *PB_Respons {
	if m != nil {
		return m.Respons
	}
	return nil
}

type PB_RequestMsgAddOne struct {
	Message *PB_Message    `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
	User    *PB_UserWithMe `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
}

func (m *PB_RequestMsgAddOne) Reset()                    { *m = PB_RequestMsgAddOne{} }
func (m *PB_RequestMsgAddOne) String() string            { return proto.CompactTextString(m) }
func (*PB_RequestMsgAddOne) ProtoMessage()               {}
func (*PB_RequestMsgAddOne) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PB_RequestMsgAddOne) GetMessage() *PB_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PB_RequestMsgAddOne) GetUser() *PB_UserWithMe {
	if m != nil {
		return m.User
	}
	return nil
}

type PB_ResponsMsgAddOne struct {
	Respons *PB_Respons `protobuf:"bytes,1,opt,name=Respons" json:"Respons,omitempty"`
}

func (m *PB_ResponsMsgAddOne) Reset()                    { *m = PB_ResponsMsgAddOne{} }
func (m *PB_ResponsMsgAddOne) String() string            { return proto.CompactTextString(m) }
func (*PB_ResponsMsgAddOne) ProtoMessage()               {}
func (*PB_ResponsMsgAddOne) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PB_ResponsMsgAddOne) GetRespons() *PB_Respons {
	if m != nil {
		return m.Respons
	}
	return nil
}

type PB_PushMsgAddMany struct {
	Messages []*PB_Message    `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
	Users    []*PB_UserWithMe `protobuf:"bytes,2,rep,name=Users" json:"Users,omitempty"`
}

func (m *PB_PushMsgAddMany) Reset()                    { *m = PB_PushMsgAddMany{} }
func (m *PB_PushMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_PushMsgAddMany) ProtoMessage()               {}
func (*PB_PushMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PB_PushMsgAddMany) GetMessages() []*PB_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PB_PushMsgAddMany) GetUsers() []*PB_UserWithMe {
	if m != nil {
		return m.Users
	}
	return nil
}

type PB_ResultMsgAddMany struct {
	Respons *PB_Respons `protobuf:"bytes,1,opt,name=Respons" json:"Respons,omitempty"`
}

func (m *PB_ResultMsgAddMany) Reset()                    { *m = PB_ResultMsgAddMany{} }
func (m *PB_ResultMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_ResultMsgAddMany) ProtoMessage()               {}
func (*PB_ResultMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PB_ResultMsgAddMany) GetRespons() *PB_Respons {
	if m != nil {
		return m.Respons
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_UserWithMe)(nil), "PB_UserWithMe")
	proto.RegisterType((*PB_Message)(nil), "PB_Message")
	proto.RegisterType((*PB_Respons)(nil), "PB_Respons")
	proto.RegisterType((*PB_Request)(nil), "PB_Request")
	proto.RegisterType((*PB_RequestMsgAddMany)(nil), "PB_RequestMsgAddMany")
	proto.RegisterType((*PB_ResponsMsgAddMany)(nil), "PB_ResponsMsgAddMany")
	proto.RegisterType((*PB_RequestMsgAddOne)(nil), "PB_RequestMsgAddOne")
	proto.RegisterType((*PB_ResponsMsgAddOne)(nil), "PB_ResponsMsgAddOne")
	proto.RegisterType((*PB_PushMsgAddMany)(nil), "PB_PushMsgAddMany")
	proto.RegisterType((*PB_ResultMsgAddMany)(nil), "PB_ResultMsgAddMany")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *PB_Message, opts ...grpc.CallOption) (*PB_UserWithMe, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *PB_Message, opts ...grpc.CallOption) (*PB_UserWithMe, error) {
	out := new(PB_UserWithMe)
	err := grpc.Invoke(ctx, "/Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *PB_Message) (*PB_UserWithMe, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*PB_Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "global.proto",
}

func init() { proto.RegisterFile("global.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x5f, 0x4d, 0x32, 0x69, 0xd3, 0x76, 0x5b, 0x90, 0x55, 0xa1, 0xaa, 0xb2, 0x5a, 0x48,
	0x25, 0x94, 0x43, 0xe1, 0x08, 0x87, 0x84, 0x52, 0x1a, 0xa8, 0xc1, 0x72, 0x52, 0x90, 0xb8, 0x84,
	0x4d, 0x3c, 0xa4, 0x96, 0x9c, 0xac, 0xd9, 0xdd, 0x44, 0xcd, 0x8f, 0xe4, 0xdf, 0xf0, 0x03, 0xd0,
	0x7e, 0xd8, 0x71, 0x53, 0x90, 0xe0, 0xc0, 0xcd, 0xf3, 0xde, 0x1b, 0xcf, 0xdb, 0x37, 0xeb, 0x04,
	0x36, 0x27, 0x31, 0x1b, 0xd1, 0xb8, 0x9d, 0x70, 0x26, 0x99, 0xfb, 0xa3, 0x08, 0x5b, 0x7e, 0x77,
	0x78, 0x2d, 0x90, 0x7f, 0x8e, 0xe4, 0x8d, 0x87, 0xe4, 0x11, 0x6c, 0xa8, 0xaa, 0x17, 0x3a, 0x85,
	0xa3, 0x42, 0xab, 0x12, 0xd8, 0x8a, 0x1c, 0x40, 0x4d, 0x3d, 0x7d, 0xa0, 0x53, 0x74, 0x8a, 0x47,
	0x85, 0x56, 0x3d, 0xc8, 0x6a, 0xf2, 0x18, 0xea, 0x17, 0x11, 0x17, 0x52, 0x93, 0x25, 0x4d, 0xae,
	0x00, 0xd5, 0x79, 0x45, 0x2d, 0x59, 0x36, 0x9d, 0x69, 0x4d, 0xf6, 0xa1, 0xd2, 0x19, 0xb1, 0xb9,
	0x74, 0x2a, 0x9a, 0x30, 0x85, 0xea, 0xb8, 0x98, 0xc7, 0xb1, 0xee, 0xd8, 0x30, 0x1d, 0x69, 0xad,
	0x66, 0x75, 0x16, 0x54, 0x52, 0x7e, 0xcd, 0x63, 0xa7, 0x6a, 0x66, 0x65, 0x00, 0x79, 0x02, 0x4d,
	0x9f, 0x47, 0x0b, 0x3a, 0x5e, 0xfa, 0x9c, 0x7d, 0x8b, 0x62, 0x74, 0x6a, 0xfa, 0x14, 0x6b, 0xa8,
	0x9a, 0xeb, 0xdf, 0xb0, 0x19, 0x3a, 0x75, 0x33, 0x57, 0x17, 0xe4, 0x08, 0x1a, 0xd7, 0x49, 0x48,
	0x25, 0x86, 0x83, 0x68, 0x8a, 0x0e, 0xe8, 0xd6, 0x3c, 0x44, 0x0e, 0x01, 0x3a, 0x49, 0xf2, 0x09,
	0xb9, 0x88, 0xd8, 0xcc, 0x69, 0x68, 0x41, 0x0e, 0x71, 0x7f, 0x96, 0x01, 0xfc, 0xee, 0xd0, 0x43,
	0x21, 0xe8, 0x44, 0xcb, 0xed, 0xe3, 0x7b, 0x5c, 0xea, 0x40, 0xeb, 0x41, 0x0e, 0x21, 0x0e, 0x54,
	0x03, 0xc6, 0xa6, 0x8a, 0x34, 0x99, 0xa6, 0x65, 0x6e, 0x0d, 0x2a, 0xcf, 0x52, 0xb6, 0x86, 0x43,
	0x00, 0x25, 0x19, 0x2c, 0x13, 0xec, 0x85, 0x3a, 0xce, 0x4a, 0x90, 0x43, 0xc8, 0x31, 0x6c, 0xd9,
	0xf7, 0x5b, 0x49, 0x45, 0x4b, 0xee, 0x82, 0x84, 0x40, 0x79, 0x80, 0xb7, 0xd2, 0x86, 0xab, 0x9f,
	0x55, 0xb0, 0x6f, 0x6e, 0x25, 0xa7, 0xef, 0x04, 0x9b, 0xa5, 0xc1, 0x66, 0x80, 0xf2, 0xd3, 0x13,
	0xdd, 0xa5, 0x97, 0x06, 0x6a, 0x2b, 0xb5, 0xaa, 0x9e, 0xe8, 0x4b, 0xca, 0x31, 0xd4, 0x59, 0x56,
	0x82, 0xac, 0x56, 0x6f, 0x7c, 0xcd, 0x51, 0x65, 0xe7, 0x09, 0x1d, 0x66, 0x29, 0x58, 0x01, 0xa4,
	0x05, 0xdb, 0xb6, 0x38, 0xc7, 0x45, 0x34, 0x46, 0x4f, 0xe8, 0x3c, 0x4b, 0xc1, 0x3a, 0xac, 0x66,
	0xf7, 0x19, 0x97, 0xbd, 0xd0, 0xd9, 0x34, 0x59, 0x98, 0x8a, 0xb8, 0xb0, 0xe9, 0x23, 0xf2, 0x3e,
	0xe2, 0x4c, 0xef, 0x6b, 0x4b, 0xb3, 0x77, 0x30, 0xd2, 0x06, 0xd2, 0x47, 0xbe, 0x40, 0x1e, 0xe0,
	0x18, 0xa3, 0x85, 0xdd, 0x6c, 0x53, 0x2b, 0x7f, 0xc3, 0x90, 0x67, 0xb0, 0x6b, 0xd0, 0x73, 0x8c,
	0x31, 0xbd, 0x08, 0xdb, 0x5a, 0x7e, 0x9f, 0x50, 0x27, 0xec, 0x65, 0xe3, 0x77, 0xcc, 0x09, 0x33,
	0x40, 0xf9, 0x1e, 0x30, 0x7f, 0x2e, 0x6e, 0x9c, 0x5d, 0x93, 0x99, 0xa9, 0xc8, 0x29, 0xec, 0x78,
	0x62, 0x72, 0x11, 0xc5, 0x38, 0xbc, 0x62, 0x63, 0x1a, 0xf7, 0xf9, 0xd8, 0x21, 0x3a, 0xf0, 0x6d,
	0x8b, 0xa7, 0x30, 0x39, 0x81, 0x66, 0x2a, 0xed, 0x4b, 0x2a, 0xe7, 0xc2, 0xd9, 0xb3, 0xfb, 0x34,
	0xa8, 0x01, 0xdd, 0x63, 0x7d, 0xeb, 0x02, 0x14, 0x09, 0x9b, 0x99, 0xbc, 0x8c, 0xd8, 0x7e, 0xc2,
	0x6b, 0xaa, 0xef, 0x73, 0x14, 0xf2, 0x8f, 0x2a, 0x84, 0xfd, 0x95, 0xca, 0x13, 0x93, 0x4e, 0x18,
	0x7a, 0x74, 0xb6, 0x24, 0x4f, 0xa1, 0x66, 0x2f, 0x91, 0xea, 0x28, 0xb5, 0x1a, 0x67, 0x8d, 0xf6,
	0xea, 0xaa, 0x07, 0x19, 0x49, 0x8e, 0xa1, 0xa2, 0x2e, 0xab, 0x70, 0x8a, 0x5a, 0xd5, 0x6c, 0xdf,
	0xf9, 0x81, 0x09, 0x0c, 0xe9, 0xbe, 0xb2, 0x63, 0xb4, 0xe5, 0xdc, 0x98, 0x13, 0xa8, 0x5a, 0x50,
	0xfb, 0xb2, 0x53, 0x2c, 0x14, 0xa4, 0x9c, 0xfb, 0x15, 0xf6, 0xd6, 0x5d, 0x7e, 0x9c, 0xa1, 0xea,
	0xb6, 0x3e, 0xf2, 0xdd, 0xa9, 0xc7, 0x94, 0x23, 0x2e, 0x94, 0x95, 0x0b, 0xfd, 0xd1, 0xdd, 0x77,
	0xa8, 0x39, 0xf7, 0xa5, 0x9d, 0x90, 0x33, 0x68, 0x27, 0xfc, 0x8d, 0xbf, 0x11, 0xec, 0xfa, 0xdd,
	0xa1, 0x5a, 0xf7, 0xff, 0x8b, 0x30, 0x73, 0x38, 0x8f, 0xe5, 0x3f, 0x27, 0x78, 0xf6, 0x02, 0xaa,
	0x6f, 0x39, 0xa2, 0x44, 0x4e, 0x4e, 0xa1, 0xd6, 0xa7, 0xcb, 0x4b, 0x8c, 0x63, 0x46, 0xf2, 0x8e,
	0x0e, 0xd6, 0x06, 0xbb, 0x0f, 0xba, 0x0f, 0xa1, 0x16, 0xf1, 0xf6, 0x54, 0xb4, 0x93, 0x51, 0xb7,
	0xe8, 0x77, 0x2f, 0x4b, 0x7e, 0xe1, 0x4b, 0xe1, 0x76, 0xb4, 0xa1, 0xff, 0x4e, 0x9e, 0xff, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x95, 0x28, 0x25, 0xd0, 0x5e, 0x06, 0x00, 0x00,
}
