// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_rpc_sync.proto

package x

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// /////////////////////////////
type PB_SyncParam_GetDirectUpdates struct {
	LastId int64 `protobuf:"varint,1,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncParam_GetDirectUpdates) Reset()                    { *m = PB_SyncParam_GetDirectUpdates{} }
func (m *PB_SyncParam_GetDirectUpdates) String() string            { return proto.CompactTextString(m) }
func (*PB_SyncParam_GetDirectUpdates) ProtoMessage()               {}
func (*PB_SyncParam_GetDirectUpdates) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *PB_SyncParam_GetDirectUpdates) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type PB_SyncResponse_GetDirectUpdates struct {
	// new mssages
	NewMessages           []*PB_MessageView           `protobuf:"bytes,1,rep,name=NewMessages" json:"NewMessages,omitempty"`
	ChatFiles             []*PB_MessageFileView       `protobuf:"bytes,2,rep,name=ChatFiles" json:"ChatFiles,omitempty"`
	Chats                 []*PB_ChatView              `protobuf:"bytes,3,rep,name=Chats" json:"Chats,omitempty"`
	Users                 []*PB_UserView              `protobuf:"bytes,6,rep,name=Users" json:"Users,omitempty"`
	MessagesChangeIds     []*PB_UpdateMessageId       `protobuf:"bytes,10,rep,name=MessagesChangeIds" json:"MessagesChangeIds,omitempty"`
	MessagesFileChangeIds []*PB_UpdateMessageId       `protobuf:"bytes,15,rep,name=MessagesFileChangeIds" json:"MessagesFileChangeIds,omitempty"`
	MessagesToUpdate      []*PB_UpdateMessageToEdit   `protobuf:"bytes,11,rep,name=MessagesToUpdate" json:"MessagesToUpdate,omitempty"`
	MessagesToDelete      []*PB_UpdateMessageToDelete `protobuf:"bytes,12,rep,name=MessagesToDelete" json:"MessagesToDelete,omitempty"`
	// messages meta info
	MessagesDelivierdToServer []*PB_UpdateMessageMeta `protobuf:"bytes,20,rep,name=MessagesDelivierdToServer" json:"MessagesDelivierdToServer,omitempty"`
	MessagesDelivierdToPeer   []*PB_UpdateMessageMeta `protobuf:"bytes,21,rep,name=MessagesDelivierdToPeer" json:"MessagesDelivierdToPeer,omitempty"`
	MessagesSeenByPeer        []*PB_UpdateMessageMeta `protobuf:"bytes,22,rep,name=MessagesSeenByPeer" json:"MessagesSeenByPeer,omitempty"`
	MessagesDeletedFromServer []*PB_UpdateMessageMeta `protobuf:"bytes,23,rep,name=MessagesDeletedFromServer" json:"MessagesDeletedFromServer,omitempty"`
	// room updates
	RoomActionDoing []*PB_UpdateRoomActionDoing `protobuf:"bytes,30,rep,name=RoomActionDoing" json:"RoomActionDoing,omitempty"`
	LastId          int64                       `protobuf:"varint,50,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncResponse_GetDirectUpdates) Reset()         { *m = PB_SyncResponse_GetDirectUpdates{} }
func (m *PB_SyncResponse_GetDirectUpdates) String() string { return proto.CompactTextString(m) }
func (*PB_SyncResponse_GetDirectUpdates) ProtoMessage()    {}
func (*PB_SyncResponse_GetDirectUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{1}
}

func (m *PB_SyncResponse_GetDirectUpdates) GetNewMessages() []*PB_MessageView {
	if m != nil {
		return m.NewMessages
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetChatFiles() []*PB_MessageFileView {
	if m != nil {
		return m.ChatFiles
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetChats() []*PB_ChatView {
	if m != nil {
		return m.Chats
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetUsers() []*PB_UserView {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesChangeIds() []*PB_UpdateMessageId {
	if m != nil {
		return m.MessagesChangeIds
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesFileChangeIds() []*PB_UpdateMessageId {
	if m != nil {
		return m.MessagesFileChangeIds
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesToUpdate() []*PB_UpdateMessageToEdit {
	if m != nil {
		return m.MessagesToUpdate
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesToDelete() []*PB_UpdateMessageToDelete {
	if m != nil {
		return m.MessagesToDelete
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesDelivierdToServer() []*PB_UpdateMessageMeta {
	if m != nil {
		return m.MessagesDelivierdToServer
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesDelivierdToPeer() []*PB_UpdateMessageMeta {
	if m != nil {
		return m.MessagesDelivierdToPeer
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesSeenByPeer() []*PB_UpdateMessageMeta {
	if m != nil {
		return m.MessagesSeenByPeer
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetMessagesDeletedFromServer() []*PB_UpdateMessageMeta {
	if m != nil {
		return m.MessagesDeletedFromServer
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetRoomActionDoing() []*PB_UpdateRoomActionDoing {
	if m != nil {
		return m.RoomActionDoing
	}
	return nil
}

func (m *PB_SyncResponse_GetDirectUpdates) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

// ////////////////////////////
type PB_SyncParam_GetGeneralUpdates struct {
	LastId int64 `protobuf:"varint,1,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncParam_GetGeneralUpdates) Reset()                    { *m = PB_SyncParam_GetGeneralUpdates{} }
func (m *PB_SyncParam_GetGeneralUpdates) String() string            { return proto.CompactTextString(m) }
func (*PB_SyncParam_GetGeneralUpdates) ProtoMessage()               {}
func (*PB_SyncParam_GetGeneralUpdates) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *PB_SyncParam_GetGeneralUpdates) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type PB_SyncResponse_GetGeneralUpdates struct {
	// PB_GeneralUpdatesView Updates = 1;
	UserBlockedByMe []*PB_UpdateUserBlocked `protobuf:"bytes,50,rep,name=UserBlockedByMe" json:"UserBlockedByMe,omitempty"`
	UserBlockedMe   []*PB_UpdateUserBlocked `protobuf:"bytes,51,rep,name=UserBlockedMe" json:"UserBlockedMe,omitempty"`
	LastId          int64                   `protobuf:"varint,60,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncResponse_GetGeneralUpdates) Reset()         { *m = PB_SyncResponse_GetGeneralUpdates{} }
func (m *PB_SyncResponse_GetGeneralUpdates) String() string { return proto.CompactTextString(m) }
func (*PB_SyncResponse_GetGeneralUpdates) ProtoMessage()    {}
func (*PB_SyncResponse_GetGeneralUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{3}
}

func (m *PB_SyncResponse_GetGeneralUpdates) GetUserBlockedByMe() []*PB_UpdateUserBlocked {
	if m != nil {
		return m.UserBlockedByMe
	}
	return nil
}

func (m *PB_SyncResponse_GetGeneralUpdates) GetUserBlockedMe() []*PB_UpdateUserBlocked {
	if m != nil {
		return m.UserBlockedMe
	}
	return nil
}

func (m *PB_SyncResponse_GetGeneralUpdates) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

// ////////////////////////////
type PB_SyncParam_GetNotifyUpdates struct {
	LastId int64 `protobuf:"varint,1,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncParam_GetNotifyUpdates) Reset()                    { *m = PB_SyncParam_GetNotifyUpdates{} }
func (m *PB_SyncParam_GetNotifyUpdates) String() string            { return proto.CompactTextString(m) }
func (*PB_SyncParam_GetNotifyUpdates) ProtoMessage()               {}
func (*PB_SyncParam_GetNotifyUpdates) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *PB_SyncParam_GetNotifyUpdates) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type PB_SyncResponse_GetNotifyUpdates struct {
	Updates *PB_NotifyUpdatesView `protobuf:"bytes,1,opt,name=Updates" json:"Updates,omitempty"`
	LastId  int64                 `protobuf:"varint,50,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncResponse_GetNotifyUpdates) Reset()         { *m = PB_SyncResponse_GetNotifyUpdates{} }
func (m *PB_SyncResponse_GetNotifyUpdates) String() string { return proto.CompactTextString(m) }
func (*PB_SyncResponse_GetNotifyUpdates) ProtoMessage()    {}
func (*PB_SyncResponse_GetNotifyUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{5}
}

func (m *PB_SyncResponse_GetNotifyUpdates) GetUpdates() *PB_NotifyUpdatesView {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *PB_SyncResponse_GetNotifyUpdates) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

// ////////// SetLastSync... //////////////////
type PB_SyncParam_SetLastSyncDirectUpdateId struct {
	LastId int64 `protobuf:"varint,1,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncParam_SetLastSyncDirectUpdateId) Reset() {
	*m = PB_SyncParam_SetLastSyncDirectUpdateId{}
}
func (m *PB_SyncParam_SetLastSyncDirectUpdateId) String() string { return proto.CompactTextString(m) }
func (*PB_SyncParam_SetLastSyncDirectUpdateId) ProtoMessage()    {}
func (*PB_SyncParam_SetLastSyncDirectUpdateId) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{6}
}

func (m *PB_SyncParam_SetLastSyncDirectUpdateId) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type PB_SyncResponse_SetLastSyncDirectUpdateId struct {
}

func (m *PB_SyncResponse_SetLastSyncDirectUpdateId) Reset() {
	*m = PB_SyncResponse_SetLastSyncDirectUpdateId{}
}
func (m *PB_SyncResponse_SetLastSyncDirectUpdateId) String() string { return proto.CompactTextString(m) }
func (*PB_SyncResponse_SetLastSyncDirectUpdateId) ProtoMessage()    {}
func (*PB_SyncResponse_SetLastSyncDirectUpdateId) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{7}
}

// ////////////////////////////
type PB_SyncParam_SetLastSyncGeneralUpdateId struct {
	LastId int64 `protobuf:"varint,1,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncParam_SetLastSyncGeneralUpdateId) Reset() {
	*m = PB_SyncParam_SetLastSyncGeneralUpdateId{}
}
func (m *PB_SyncParam_SetLastSyncGeneralUpdateId) String() string { return proto.CompactTextString(m) }
func (*PB_SyncParam_SetLastSyncGeneralUpdateId) ProtoMessage()    {}
func (*PB_SyncParam_SetLastSyncGeneralUpdateId) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{8}
}

func (m *PB_SyncParam_SetLastSyncGeneralUpdateId) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type PB_SyncResponse_SetLastSyncGeneralUpdateId struct {
}

func (m *PB_SyncResponse_SetLastSyncGeneralUpdateId) Reset() {
	*m = PB_SyncResponse_SetLastSyncGeneralUpdateId{}
}
func (m *PB_SyncResponse_SetLastSyncGeneralUpdateId) String() string {
	return proto.CompactTextString(m)
}
func (*PB_SyncResponse_SetLastSyncGeneralUpdateId) ProtoMessage() {}
func (*PB_SyncResponse_SetLastSyncGeneralUpdateId) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{9}
}

// ////////////////////////////
type PB_SyncParam_SetLastSyncNotifyUpdateId struct {
	LastId int64 `protobuf:"varint,1,opt,name=LastId" json:"LastId,omitempty"`
}

func (m *PB_SyncParam_SetLastSyncNotifyUpdateId) Reset() {
	*m = PB_SyncParam_SetLastSyncNotifyUpdateId{}
}
func (m *PB_SyncParam_SetLastSyncNotifyUpdateId) String() string { return proto.CompactTextString(m) }
func (*PB_SyncParam_SetLastSyncNotifyUpdateId) ProtoMessage()    {}
func (*PB_SyncParam_SetLastSyncNotifyUpdateId) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{10}
}

func (m *PB_SyncParam_SetLastSyncNotifyUpdateId) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

type PB_SyncResponse_SetLastSyncNotifyUpdateId struct {
}

func (m *PB_SyncResponse_SetLastSyncNotifyUpdateId) Reset() {
	*m = PB_SyncResponse_SetLastSyncNotifyUpdateId{}
}
func (m *PB_SyncResponse_SetLastSyncNotifyUpdateId) String() string { return proto.CompactTextString(m) }
func (*PB_SyncResponse_SetLastSyncNotifyUpdateId) ProtoMessage()    {}
func (*PB_SyncResponse_SetLastSyncNotifyUpdateId) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{11}
}

type PB_NotifyUpdatesView struct {
	// users
	UserBlockedByMe []*PB_UpdateUserBlocked `protobuf:"bytes,50,rep,name=UserBlockedByMe" json:"UserBlockedByMe,omitempty"`
	UserBlockedMe   []*PB_UpdateUserBlocked `protobuf:"bytes,51,rep,name=UserBlockedMe" json:"UserBlockedMe,omitempty"`
}

func (m *PB_NotifyUpdatesView) Reset()                    { *m = PB_NotifyUpdatesView{} }
func (m *PB_NotifyUpdatesView) String() string            { return proto.CompactTextString(m) }
func (*PB_NotifyUpdatesView) ProtoMessage()               {}
func (*PB_NotifyUpdatesView) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

func (m *PB_NotifyUpdatesView) GetUserBlockedByMe() []*PB_UpdateUserBlocked {
	if m != nil {
		return m.UserBlockedByMe
	}
	return nil
}

func (m *PB_NotifyUpdatesView) GetUserBlockedMe() []*PB_UpdateUserBlocked {
	if m != nil {
		return m.UserBlockedMe
	}
	return nil
}

// ///////// Pushes /////////////
// use this for pushing live data - instead of hacking rpc *yResponse* types
type PB_AllLivePushes struct {
	DirectUpdates      *PB_SyncResponse_GetDirectUpdates  `protobuf:"bytes,1,opt,name=DirectUpdates" json:"DirectUpdates,omitempty"`
	GeneralUpdates     *PB_SyncResponse_GetGeneralUpdates `protobuf:"bytes,2,opt,name=GeneralUpdates" json:"GeneralUpdates,omitempty"`
	Offline_Messagings *PB_Offline_Messagings             `protobuf:"bytes,3,opt,name=Offline_Messagings,json=OfflineMessagings" json:"Offline_Messagings,omitempty"`
}

func (m *PB_AllLivePushes) Reset()                    { *m = PB_AllLivePushes{} }
func (m *PB_AllLivePushes) String() string            { return proto.CompactTextString(m) }
func (*PB_AllLivePushes) ProtoMessage()               {}
func (*PB_AllLivePushes) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{13} }

func (m *PB_AllLivePushes) GetDirectUpdates() *PB_SyncResponse_GetDirectUpdates {
	if m != nil {
		return m.DirectUpdates
	}
	return nil
}

func (m *PB_AllLivePushes) GetGeneralUpdates() *PB_SyncResponse_GetGeneralUpdates {
	if m != nil {
		return m.GeneralUpdates
	}
	return nil
}

func (m *PB_AllLivePushes) GetOffline_Messagings() *PB_Offline_Messagings {
	if m != nil {
		return m.Offline_Messagings
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_SyncParam_GetDirectUpdates)(nil), "PB_SyncParam_GetDirectUpdates")
	proto.RegisterType((*PB_SyncResponse_GetDirectUpdates)(nil), "PB_SyncResponse_GetDirectUpdates")
	proto.RegisterType((*PB_SyncParam_GetGeneralUpdates)(nil), "PB_SyncParam_GetGeneralUpdates")
	proto.RegisterType((*PB_SyncResponse_GetGeneralUpdates)(nil), "PB_SyncResponse_GetGeneralUpdates")
	proto.RegisterType((*PB_SyncParam_GetNotifyUpdates)(nil), "PB_SyncParam_GetNotifyUpdates")
	proto.RegisterType((*PB_SyncResponse_GetNotifyUpdates)(nil), "PB_SyncResponse_GetNotifyUpdates")
	proto.RegisterType((*PB_SyncParam_SetLastSyncDirectUpdateId)(nil), "PB_SyncParam_SetLastSyncDirectUpdateId")
	proto.RegisterType((*PB_SyncResponse_SetLastSyncDirectUpdateId)(nil), "PB_SyncResponse_SetLastSyncDirectUpdateId")
	proto.RegisterType((*PB_SyncParam_SetLastSyncGeneralUpdateId)(nil), "PB_SyncParam_SetLastSyncGeneralUpdateId")
	proto.RegisterType((*PB_SyncResponse_SetLastSyncGeneralUpdateId)(nil), "PB_SyncResponse_SetLastSyncGeneralUpdateId")
	proto.RegisterType((*PB_SyncParam_SetLastSyncNotifyUpdateId)(nil), "PB_SyncParam_SetLastSyncNotifyUpdateId")
	proto.RegisterType((*PB_SyncResponse_SetLastSyncNotifyUpdateId)(nil), "PB_SyncResponse_SetLastSyncNotifyUpdateId")
	proto.RegisterType((*PB_NotifyUpdatesView)(nil), "PB_NotifyUpdatesView")
	proto.RegisterType((*PB_AllLivePushes)(nil), "PB_AllLivePushes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPC_Sync service

type RPC_SyncClient interface {
	GetDirectUpdates(ctx context.Context, in *PB_SyncParam_GetDirectUpdates, opts ...grpc.CallOption) (*PB_SyncResponse_GetDirectUpdates, error)
	GetGeneralUpdates(ctx context.Context, in *PB_SyncParam_GetGeneralUpdates, opts ...grpc.CallOption) (*PB_SyncResponse_GetGeneralUpdates, error)
	GetNotifyUpdates(ctx context.Context, in *PB_SyncParam_GetNotifyUpdates, opts ...grpc.CallOption) (*PB_SyncResponse_GetNotifyUpdates, error)
	SetLastSyncDirectUpdateId(ctx context.Context, in *PB_SyncParam_SetLastSyncDirectUpdateId, opts ...grpc.CallOption) (*PB_SyncResponse_SetLastSyncDirectUpdateId, error)
	SetLastSyncGeneralUpdateId(ctx context.Context, in *PB_SyncParam_SetLastSyncGeneralUpdateId, opts ...grpc.CallOption) (*PB_SyncResponse_SetLastSyncGeneralUpdateId, error)
	SetLastSyncNotifyUpdateId(ctx context.Context, in *PB_SyncParam_SetLastSyncNotifyUpdateId, opts ...grpc.CallOption) (*PB_SyncResponse_SetLastSyncNotifyUpdateId, error)
}

type rPC_SyncClient struct {
	cc *grpc.ClientConn
}

func NewRPC_SyncClient(cc *grpc.ClientConn) RPC_SyncClient {
	return &rPC_SyncClient{cc}
}

func (c *rPC_SyncClient) GetDirectUpdates(ctx context.Context, in *PB_SyncParam_GetDirectUpdates, opts ...grpc.CallOption) (*PB_SyncResponse_GetDirectUpdates, error) {
	out := new(PB_SyncResponse_GetDirectUpdates)
	err := grpc.Invoke(ctx, "/RPC_Sync/GetDirectUpdates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPC_SyncClient) GetGeneralUpdates(ctx context.Context, in *PB_SyncParam_GetGeneralUpdates, opts ...grpc.CallOption) (*PB_SyncResponse_GetGeneralUpdates, error) {
	out := new(PB_SyncResponse_GetGeneralUpdates)
	err := grpc.Invoke(ctx, "/RPC_Sync/GetGeneralUpdates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPC_SyncClient) GetNotifyUpdates(ctx context.Context, in *PB_SyncParam_GetNotifyUpdates, opts ...grpc.CallOption) (*PB_SyncResponse_GetNotifyUpdates, error) {
	out := new(PB_SyncResponse_GetNotifyUpdates)
	err := grpc.Invoke(ctx, "/RPC_Sync/GetNotifyUpdates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPC_SyncClient) SetLastSyncDirectUpdateId(ctx context.Context, in *PB_SyncParam_SetLastSyncDirectUpdateId, opts ...grpc.CallOption) (*PB_SyncResponse_SetLastSyncDirectUpdateId, error) {
	out := new(PB_SyncResponse_SetLastSyncDirectUpdateId)
	err := grpc.Invoke(ctx, "/RPC_Sync/SetLastSyncDirectUpdateId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPC_SyncClient) SetLastSyncGeneralUpdateId(ctx context.Context, in *PB_SyncParam_SetLastSyncGeneralUpdateId, opts ...grpc.CallOption) (*PB_SyncResponse_SetLastSyncGeneralUpdateId, error) {
	out := new(PB_SyncResponse_SetLastSyncGeneralUpdateId)
	err := grpc.Invoke(ctx, "/RPC_Sync/SetLastSyncGeneralUpdateId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPC_SyncClient) SetLastSyncNotifyUpdateId(ctx context.Context, in *PB_SyncParam_SetLastSyncNotifyUpdateId, opts ...grpc.CallOption) (*PB_SyncResponse_SetLastSyncNotifyUpdateId, error) {
	out := new(PB_SyncResponse_SetLastSyncNotifyUpdateId)
	err := grpc.Invoke(ctx, "/RPC_Sync/SetLastSyncNotifyUpdateId", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPC_Sync service

type RPC_SyncServer interface {
	GetDirectUpdates(context.Context, *PB_SyncParam_GetDirectUpdates) (*PB_SyncResponse_GetDirectUpdates, error)
	GetGeneralUpdates(context.Context, *PB_SyncParam_GetGeneralUpdates) (*PB_SyncResponse_GetGeneralUpdates, error)
	GetNotifyUpdates(context.Context, *PB_SyncParam_GetNotifyUpdates) (*PB_SyncResponse_GetNotifyUpdates, error)
	SetLastSyncDirectUpdateId(context.Context, *PB_SyncParam_SetLastSyncDirectUpdateId) (*PB_SyncResponse_SetLastSyncDirectUpdateId, error)
	SetLastSyncGeneralUpdateId(context.Context, *PB_SyncParam_SetLastSyncGeneralUpdateId) (*PB_SyncResponse_SetLastSyncGeneralUpdateId, error)
	SetLastSyncNotifyUpdateId(context.Context, *PB_SyncParam_SetLastSyncNotifyUpdateId) (*PB_SyncResponse_SetLastSyncNotifyUpdateId, error)
}

func RegisterRPC_SyncServer(s *grpc.Server, srv RPC_SyncServer) {
	s.RegisterService(&_RPC_Sync_serviceDesc, srv)
}

func _RPC_Sync_GetDirectUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_SyncParam_GetDirectUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPC_SyncServer).GetDirectUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPC_Sync/GetDirectUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPC_SyncServer).GetDirectUpdates(ctx, req.(*PB_SyncParam_GetDirectUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Sync_GetGeneralUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_SyncParam_GetGeneralUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPC_SyncServer).GetGeneralUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPC_Sync/GetGeneralUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPC_SyncServer).GetGeneralUpdates(ctx, req.(*PB_SyncParam_GetGeneralUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Sync_GetNotifyUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_SyncParam_GetNotifyUpdates)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPC_SyncServer).GetNotifyUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPC_Sync/GetNotifyUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPC_SyncServer).GetNotifyUpdates(ctx, req.(*PB_SyncParam_GetNotifyUpdates))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Sync_SetLastSyncDirectUpdateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_SyncParam_SetLastSyncDirectUpdateId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPC_SyncServer).SetLastSyncDirectUpdateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPC_Sync/SetLastSyncDirectUpdateId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPC_SyncServer).SetLastSyncDirectUpdateId(ctx, req.(*PB_SyncParam_SetLastSyncDirectUpdateId))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Sync_SetLastSyncGeneralUpdateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_SyncParam_SetLastSyncGeneralUpdateId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPC_SyncServer).SetLastSyncGeneralUpdateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPC_Sync/SetLastSyncGeneralUpdateId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPC_SyncServer).SetLastSyncGeneralUpdateId(ctx, req.(*PB_SyncParam_SetLastSyncGeneralUpdateId))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Sync_SetLastSyncNotifyUpdateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_SyncParam_SetLastSyncNotifyUpdateId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPC_SyncServer).SetLastSyncNotifyUpdateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPC_Sync/SetLastSyncNotifyUpdateId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPC_SyncServer).SetLastSyncNotifyUpdateId(ctx, req.(*PB_SyncParam_SetLastSyncNotifyUpdateId))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_Sync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RPC_Sync",
	HandlerType: (*RPC_SyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectUpdates",
			Handler:    _RPC_Sync_GetDirectUpdates_Handler,
		},
		{
			MethodName: "GetGeneralUpdates",
			Handler:    _RPC_Sync_GetGeneralUpdates_Handler,
		},
		{
			MethodName: "GetNotifyUpdates",
			Handler:    _RPC_Sync_GetNotifyUpdates_Handler,
		},
		{
			MethodName: "SetLastSyncDirectUpdateId",
			Handler:    _RPC_Sync_SetLastSyncDirectUpdateId_Handler,
		},
		{
			MethodName: "SetLastSyncGeneralUpdateId",
			Handler:    _RPC_Sync_SetLastSyncGeneralUpdateId_Handler,
		},
		{
			MethodName: "SetLastSyncNotifyUpdateId",
			Handler:    _RPC_Sync_SetLastSyncNotifyUpdateId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_rpc_sync.proto",
}

func init() { proto.RegisterFile("pb_rpc_sync.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x4e, 0xdb, 0x48,
	0x14, 0x96, 0xc9, 0x2e, 0xb0, 0x87, 0x9f, 0x24, 0xb3, 0xfc, 0x98, 0x48, 0xcb, 0x42, 0x2e, 0x16,
	0x16, 0x2a, 0x57, 0x84, 0x8b, 0x56, 0x6a, 0xa5, 0x36, 0x3f, 0x40, 0x53, 0x11, 0xb0, 0x1c, 0xa8,
	0xaa, 0xde, 0x58, 0x4e, 0x7c, 0x08, 0x16, 0x8e, 0x6d, 0x79, 0x4c, 0x68, 0x1e, 0xa1, 0xf7, 0x7d,
	0x99, 0x3e, 0x53, 0xa5, 0x3e, 0x43, 0x35, 0x8e, 0xad, 0x78, 0xfc, 0x97, 0xa8, 0x37, 0xbd, 0x8b,
	0xcf, 0xf9, 0xbe, 0x6f, 0xce, 0x99, 0xc9, 0x77, 0x66, 0xa0, 0xec, 0xf4, 0x54, 0xd7, 0xe9, 0xab,
	0x74, 0x6c, 0xf5, 0x25, 0xc7, 0xb5, 0x3d, 0xbb, 0xb2, 0xee, 0xf4, 0x54, 0xb4, 0x1e, 0x87, 0x34,
	0xf2, 0x3d, 0x32, 0xf0, 0x29, 0xfc, 0x2e, 0x39, 0x3d, 0xf5, 0xd1, 0xd1, 0x35, 0x0f, 0xc3, 0x08,
	0x13, 0xb1, 0xef, 0xee, 0x4c, 0xc3, 0x0a, 0x43, 0xd5, 0x17, 0xf0, 0x8f, 0xdc, 0x50, 0xbb, 0x63,
	0xab, 0x2f, 0x6b, 0xae, 0x36, 0x54, 0x2f, 0xd0, 0x6b, 0x19, 0x2e, 0xf6, 0xbd, 0xdb, 0x09, 0x93,
	0x6c, 0xc1, 0xe2, 0xa5, 0x46, 0xbd, 0xb6, 0x2e, 0x0a, 0x7b, 0xc2, 0x61, 0x41, 0x09, 0xbe, 0xaa,
	0x5f, 0x96, 0x60, 0x2f, 0x60, 0x2a, 0x48, 0x1d, 0xdb, 0xa2, 0x98, 0x24, 0x9f, 0xc0, 0xca, 0x15,
	0x3e, 0x75, 0x90, 0x52, 0x6d, 0x80, 0x54, 0x14, 0xf6, 0x0a, 0x87, 0x2b, 0xb5, 0xa2, 0x24, 0x37,
	0xd4, 0x20, 0xf6, 0xc1, 0xc0, 0x27, 0x25, 0x8a, 0x21, 0x27, 0xf0, 0x57, 0xf3, 0x5e, 0xf3, 0xce,
	0x0d, 0x13, 0xa9, 0xb8, 0xe0, 0x13, 0xfe, 0x8e, 0x10, 0x58, 0xdc, 0x27, 0x4d, 0x51, 0xa4, 0x0a,
	0x7f, 0xb2, 0x0f, 0x2a, 0x16, 0x7c, 0xf8, 0x2a, 0x83, 0xb3, 0x80, 0x8f, 0x9b, 0xa4, 0x18, 0xe6,
	0x96, 0xa2, 0x4b, 0xc5, 0xc5, 0x29, 0x86, 0x05, 0x26, 0x18, 0x3f, 0x45, 0xea, 0x50, 0x0e, 0xcb,
	0x68, 0xde, 0x6b, 0xd6, 0x00, 0xdb, 0x3a, 0x15, 0x61, 0x5a, 0xc2, 0xa4, 0xab, 0x00, 0xd2, 0xd6,
	0x95, 0x24, 0x9a, 0xb4, 0x61, 0x33, 0x0c, 0xb2, 0xda, 0xa6, 0x32, 0xc5, 0x6c, 0x99, 0x74, 0x06,
	0x69, 0x42, 0x29, 0x4c, 0xdc, 0xd8, 0x13, 0x8e, 0xb8, 0xe2, 0xab, 0x6c, 0x27, 0x54, 0x6e, 0xec,
	0x33, 0xdd, 0xf0, 0x94, 0x04, 0x81, 0x9c, 0x45, 0x45, 0x5a, 0x68, 0xa2, 0x87, 0xe2, 0xaa, 0x2f,
	0xb2, 0x93, 0x22, 0x32, 0x01, 0x28, 0x09, 0x0a, 0xe9, 0xc2, 0x4e, 0x18, 0x6b, 0xa1, 0x69, 0x8c,
	0x0c, 0x74, 0xf5, 0x1b, 0xbb, 0x8b, 0xee, 0x08, 0x5d, 0x71, 0xc3, 0xd7, 0xdb, 0x4c, 0xe8, 0x75,
	0xd0, 0xd3, 0x94, 0x6c, 0x1e, 0xb9, 0x86, 0xed, 0x94, 0xa4, 0x8c, 0xe8, 0x8a, 0x9b, 0x79, 0x92,
	0x59, 0x2c, 0x72, 0x06, 0x24, 0x4c, 0x75, 0x11, 0xad, 0xc6, 0xd8, 0xd7, 0xda, 0xca, 0xd3, 0x4a,
	0x21, 0xc4, 0x9a, 0x45, 0x0f, 0xf5, 0x73, 0xd7, 0x1e, 0x06, 0xcd, 0x6e, 0xcf, 0xdb, 0x2c, 0xcf,
	0x23, 0x4d, 0x28, 0x2a, 0xb6, 0x3d, 0xac, 0xf7, 0x3d, 0xc3, 0xb6, 0x5a, 0xb6, 0x61, 0x0d, 0xc4,
	0xdd, 0xf8, 0x39, 0xc4, 0x00, 0x4a, 0x9c, 0x11, 0xf1, 0x62, 0x8d, 0xf3, 0xe2, 0x4b, 0xd8, 0x8d,
	0x9b, 0xf8, 0x02, 0x2d, 0x74, 0x35, 0x73, 0x96, 0x8b, 0xbf, 0x09, 0xb0, 0x9f, 0xe2, 0xe2, 0x18,
	0xfb, 0x0d, 0x14, 0x99, 0x43, 0x1a, 0xa6, 0xdd, 0x7f, 0x40, 0xbd, 0x31, 0xee, 0xa0, 0x58, 0x8b,
	0xef, 0x43, 0x04, 0xa0, 0xc4, 0xd1, 0xe4, 0x15, 0xac, 0x45, 0x42, 0x1d, 0x14, 0x4f, 0xf3, 0xe8,
	0x3c, 0x36, 0x52, 0xfb, 0x6b, 0xae, 0xf6, 0x94, 0xd1, 0x75, 0x65, 0x7b, 0xc6, 0xdd, 0x78, 0x56,
	0xd3, 0x0f, 0xa9, 0x93, 0x8b, 0xe7, 0x3e, 0x87, 0xa5, 0xe0, 0xa7, 0x4f, 0x0e, 0x6a, 0xe5, 0x30,
	0xfe, 0xe8, 0x58, 0x4a, 0x2e, 0xc6, 0x9f, 0xcd, 0x5b, 0xf8, 0x8f, 0xab, 0xb2, 0x8b, 0x1e, 0xcb,
	0xb0, 0x40, 0x74, 0x56, 0xb6, 0xf5, 0xcc, 0x72, 0x8f, 0xe1, 0xff, 0x78, 0xb9, 0x99, 0x22, 0xd5,
	0x3a, 0x1c, 0x64, 0x2d, 0xc7, 0x1d, 0x6a, 0xce, 0x7a, 0xcf, 0xe0, 0x28, 0x67, 0xbd, 0x98, 0x4a,
	0x5e, 0x7f, 0xd1, 0xdd, 0xfa, 0xe5, 0xfe, 0x78, 0x91, 0xea, 0x57, 0x01, 0x36, 0xd2, 0x0e, 0xe2,
	0xf7, 0xfe, 0x47, 0xab, 0x3f, 0x04, 0x28, 0xc9, 0x0d, 0xb5, 0x6e, 0x9a, 0x97, 0xc6, 0x08, 0xe5,
	0x47, 0x7a, 0x8f, 0x94, 0x5c, 0xc0, 0x1a, 0x77, 0x1d, 0x06, 0xff, 0xa4, 0x7d, 0x69, 0xd6, 0xbd,
	0xa9, 0xf0, 0x3c, 0xf2, 0x1e, 0xd6, 0x79, 0x47, 0x8a, 0x0b, 0xbe, 0x52, 0x55, 0x9a, 0xe9, 0x5d,
	0x25, 0xc6, 0x64, 0x43, 0xf2, 0x7a, 0xf2, 0x04, 0x08, 0xae, 0x54, 0xc3, 0x1a, 0xb0, 0x9b, 0x93,
	0xe9, 0x6d, 0x31, 0xbd, 0x64, 0x56, 0x29, 0x07, 0xb1, 0x69, 0xa8, 0xf6, 0xfd, 0x0f, 0x58, 0x56,
	0xe4, 0xa6, 0xbf, 0x3a, 0xb9, 0x85, 0x52, 0xe2, 0xea, 0xdf, 0x95, 0x72, 0xdf, 0x15, 0x95, 0xd9,
	0xbb, 0x40, 0x3e, 0x42, 0x39, 0x39, 0x8b, 0xfe, 0x95, 0xf2, 0x47, 0x5d, 0x65, 0x8e, 0x4d, 0x09,
	0x0a, 0xe6, 0x1d, 0x9f, 0x2c, 0x98, 0xcb, 0xa7, 0x17, 0xcc, 0x4b, 0x38, 0xb0, 0x93, 0x6d, 0xef,
	0x03, 0x69, 0xbe, 0x39, 0x50, 0x39, 0x92, 0xe6, 0xb6, 0x3b, 0xa1, 0x50, 0xc9, 0x71, 0xf8, 0xa1,
	0x34, 0xe7, 0x2c, 0xa8, 0x1c, 0x4b, 0xf3, 0x5b, 0x3e, 0xd6, 0x66, 0xcc, 0xe5, 0xd9, 0x6d, 0xf2,
	0xc0, 0xfc, 0x36, 0x79, 0x6c, 0xa3, 0x0c, 0xcb, 0x86, 0x2b, 0xb1, 0x97, 0x6e, 0xef, 0x5d, 0x41,
	0x16, 0x3e, 0x09, 0x9f, 0x7b, 0x8b, 0xfe, 0xfb, 0xf5, 0xf4, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0x4f, 0xc3, 0x33, 0x19, 0x0b, 0x00, 0x00,
}
