// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_updates.proto

package x

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PB_UpdateGroupParticipants struct {
}

func (m *PB_UpdateGroupParticipants) Reset()                    { *m = PB_UpdateGroupParticipants{} }
func (m *PB_UpdateGroupParticipants) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateGroupParticipants) ProtoMessage()               {}
func (*PB_UpdateGroupParticipants) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type PB_UpdateNotifySettings struct {
}

func (m *PB_UpdateNotifySettings) Reset()                    { *m = PB_UpdateNotifySettings{} }
func (m *PB_UpdateNotifySettings) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateNotifySettings) ProtoMessage()               {}
func (*PB_UpdateNotifySettings) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

type PB_UpdateServiceNotification struct {
}

func (m *PB_UpdateServiceNotification) Reset()                    { *m = PB_UpdateServiceNotification{} }
func (m *PB_UpdateServiceNotification) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateServiceNotification) ProtoMessage()               {}
func (*PB_UpdateServiceNotification) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

// //////////////////////////////////////////////
type PB_UpdateMessageMeta struct {
	MessageId int64 `protobuf:"varint,1,opt,name=MessageId" json:"MessageId,omitempty"`
	AtTime    int64 `protobuf:"varint,2,opt,name=AtTime" json:"AtTime,omitempty"`
}

func (m *PB_UpdateMessageMeta) Reset()                    { *m = PB_UpdateMessageMeta{} }
func (m *PB_UpdateMessageMeta) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateMessageMeta) ProtoMessage()               {}
func (*PB_UpdateMessageMeta) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *PB_UpdateMessageMeta) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *PB_UpdateMessageMeta) GetAtTime() int64 {
	if m != nil {
		return m.AtTime
	}
	return 0
}

type PB_UpdateMessageId struct {
	OldMessageId int64 `protobuf:"varint,1,opt,name=OldMessageId" json:"OldMessageId,omitempty"`
	NewMessageId int64 `protobuf:"varint,2,opt,name=NewMessageId" json:"NewMessageId,omitempty"`
}

func (m *PB_UpdateMessageId) Reset()                    { *m = PB_UpdateMessageId{} }
func (m *PB_UpdateMessageId) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateMessageId) ProtoMessage()               {}
func (*PB_UpdateMessageId) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *PB_UpdateMessageId) GetOldMessageId() int64 {
	if m != nil {
		return m.OldMessageId
	}
	return 0
}

func (m *PB_UpdateMessageId) GetNewMessageId() int64 {
	if m != nil {
		return m.NewMessageId
	}
	return 0
}

type PB_UpdateMessageToEdit struct {
	MessageId int64  `protobuf:"varint,1,opt,name=MessageId" json:"MessageId,omitempty"`
	NewText   string `protobuf:"bytes,2,opt,name=NewText" json:"NewText,omitempty"`
}

func (m *PB_UpdateMessageToEdit) Reset()                    { *m = PB_UpdateMessageToEdit{} }
func (m *PB_UpdateMessageToEdit) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateMessageToEdit) ProtoMessage()               {}
func (*PB_UpdateMessageToEdit) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *PB_UpdateMessageToEdit) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *PB_UpdateMessageToEdit) GetNewText() string {
	if m != nil {
		return m.NewText
	}
	return ""
}

type PB_UpdateMessageToDelete struct {
	MessageId int64 `protobuf:"varint,1,opt,name=MessageId" json:"MessageId,omitempty"`
}

func (m *PB_UpdateMessageToDelete) Reset()                    { *m = PB_UpdateMessageToDelete{} }
func (m *PB_UpdateMessageToDelete) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateMessageToDelete) ProtoMessage()               {}
func (*PB_UpdateMessageToDelete) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *PB_UpdateMessageToDelete) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type PB_UpdateRoomActionDoing struct {
	//    int64 ChatId = 1;
	RoomKey    string              `protobuf:"bytes,2,opt,name=RoomKey" json:"RoomKey,omitempty"`
	ActionType RoomActionDoingEnum `protobuf:"varint,3,opt,name=ActionType,enum=RoomActionDoingEnum" json:"ActionType,omitempty"`
}

func (m *PB_UpdateRoomActionDoing) Reset()                    { *m = PB_UpdateRoomActionDoing{} }
func (m *PB_UpdateRoomActionDoing) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateRoomActionDoing) ProtoMessage()               {}
func (*PB_UpdateRoomActionDoing) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *PB_UpdateRoomActionDoing) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *PB_UpdateRoomActionDoing) GetActionType() RoomActionDoingEnum {
	if m != nil {
		return m.ActionType
	}
	return RoomActionDoingEnum_UNKNOWN_ROOM_ACTION_DOING
}

type PB_UpdateUserBlocked struct {
	UserId  int32 `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	Blocked bool  `protobuf:"varint,2,opt,name=Blocked" json:"Blocked,omitempty"`
}

func (m *PB_UpdateUserBlocked) Reset()                    { *m = PB_UpdateUserBlocked{} }
func (m *PB_UpdateUserBlocked) String() string            { return proto.CompactTextString(m) }
func (*PB_UpdateUserBlocked) ProtoMessage()               {}
func (*PB_UpdateUserBlocked) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *PB_UpdateUserBlocked) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_UpdateUserBlocked) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

func init() {
	proto.RegisterType((*PB_UpdateGroupParticipants)(nil), "PB_UpdateGroupParticipants")
	proto.RegisterType((*PB_UpdateNotifySettings)(nil), "PB_UpdateNotifySettings")
	proto.RegisterType((*PB_UpdateServiceNotification)(nil), "PB_UpdateServiceNotification")
	proto.RegisterType((*PB_UpdateMessageMeta)(nil), "PB_UpdateMessageMeta")
	proto.RegisterType((*PB_UpdateMessageId)(nil), "PB_UpdateMessageId")
	proto.RegisterType((*PB_UpdateMessageToEdit)(nil), "PB_UpdateMessageToEdit")
	proto.RegisterType((*PB_UpdateMessageToDelete)(nil), "PB_UpdateMessageToDelete")
	proto.RegisterType((*PB_UpdateRoomActionDoing)(nil), "PB_UpdateRoomActionDoing")
	proto.RegisterType((*PB_UpdateUserBlocked)(nil), "PB_UpdateUserBlocked")
}

func init() { proto.RegisterFile("pb_updates.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x4f, 0xc2, 0x30,
	0x14, 0xc5, 0x33, 0x89, 0x08, 0x37, 0x86, 0xe8, 0x42, 0x70, 0x12, 0x62, 0x48, 0x9f, 0x78, 0xe2,
	0x41, 0x7d, 0xf0, 0x15, 0x02, 0x11, 0xa2, 0xe0, 0x32, 0xc6, 0x8b, 0x31, 0x21, 0xfb, 0xb8, 0x92,
	0x2a, 0x5b, 0x9b, 0xad, 0xe3, 0xe3, 0xbf, 0x37, 0x1d, 0x65, 0x8c, 0x99, 0xe8, 0xe3, 0xef, 0x9e,
	0x73, 0xcf, 0x69, 0xda, 0xc2, 0x15, 0x77, 0x17, 0x09, 0xf7, 0x1d, 0x81, 0x71, 0x97, 0x47, 0x4c,
	0xb0, 0x66, 0x8d, 0xbb, 0x0b, 0x0c, 0x93, 0x20, 0xcf, 0x6b, 0x8a, 0x1b, 0xc5, 0xa4, 0x05, 0x4d,
	0xb3, 0xbf, 0x98, 0xa7, 0x3b, 0xcf, 0x11, 0x4b, 0xb8, 0xe9, 0x44, 0x82, 0x7a, 0x94, 0x3b, 0xa1,
	0x88, 0xc9, 0x2d, 0xdc, 0x64, 0xea, 0x94, 0x09, 0xfa, 0xb9, 0x9b, 0xa1, 0x10, 0x34, 0x5c, 0xc6,
	0xe4, 0x0e, 0x5a, 0x99, 0x34, 0xc3, 0x68, 0x4d, 0xbd, 0xbd, 0x83, 0x7a, 0x8e, 0xa0, 0x2c, 0x24,
	0xaf, 0x50, 0xcf, 0xf4, 0x09, 0xc6, 0xb1, 0xb3, 0xc4, 0x09, 0x0a, 0x47, 0x6f, 0x41, 0x55, 0xe1,
	0xd8, 0x37, 0xb4, 0xb6, 0xd6, 0x29, 0x59, 0xc7, 0x81, 0xde, 0x80, 0x72, 0x4f, 0xd8, 0x34, 0x40,
	0xe3, 0x2c, 0x95, 0x14, 0x91, 0x0f, 0xd0, 0x8b, 0x69, 0x63, 0x5f, 0x27, 0x70, 0xf9, 0xb6, 0xf2,
	0x8b, 0x71, 0x27, 0x33, 0xe9, 0x99, 0xe2, 0xe6, 0xe8, 0xd9, 0xe7, 0x9e, 0xcc, 0x88, 0x09, 0x8d,
	0x62, 0xba, 0xcd, 0x86, 0x3e, 0x15, 0xff, 0x9c, 0xd6, 0x80, 0x8b, 0x29, 0x6e, 0x6c, 0xdc, 0x8a,
	0x34, 0xb6, 0x6a, 0x1d, 0x90, 0x3c, 0x81, 0xf1, 0x3b, 0x71, 0x80, 0x2b, 0x14, 0xf8, 0x77, 0x26,
	0xf9, 0xca, 0x6d, 0x5a, 0x8c, 0x05, 0x3d, 0x4f, 0x5e, 0xe7, 0x80, 0xd1, 0x70, 0x29, 0xfb, 0xe4,
	0xe8, 0x05, 0x77, 0x87, 0x3e, 0x85, 0xfa, 0x23, 0xc0, 0xde, 0x68, 0xef, 0x38, 0x1a, 0xa5, 0xb6,
	0xd6, 0xa9, 0xdd, 0xd7, 0xbb, 0x85, 0xfd, 0x61, 0x98, 0x04, 0x56, 0xce, 0x47, 0x46, 0xb9, 0x37,
	0x9a, 0xc7, 0x18, 0xf5, 0x57, 0xcc, 0xfb, 0xc6, 0xf4, 0x15, 0x24, 0xaa, 0xe3, 0x9d, 0x5b, 0x8a,
	0x64, 0xbf, 0xb2, 0xa4, 0xfd, 0x15, 0xeb, 0x80, 0xfd, 0x6b, 0xa8, 0xd0, 0xa8, 0x2b, 0x7f, 0x99,
	0x3b, 0x2a, 0x99, 0xda, 0xbb, 0xb6, 0x75, 0xcb, 0xe9, 0x07, 0x7b, 0xf8, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x42, 0xc9, 0x81, 0x8f, 0x94, 0x02, 0x00, 0x00,
}
