// Code generated by protoc-gen-go.
// source: pb_global.proto
// DO NOT EDIT!

package x

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PB_CommandToServer struct {
	ClientCallId int64  `protobuf:"varint,1,opt,name=ClientCallId" json:"ClientCallId,omitempty"`
	Command      string `protobuf:"bytes,2,opt,name=Command" json:"Command,omitempty"`
	Data         []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *PB_CommandToServer) Reset()                    { *m = PB_CommandToServer{} }
func (m *PB_CommandToServer) String() string            { return proto.CompactTextString(m) }
func (*PB_CommandToServer) ProtoMessage()               {}
func (*PB_CommandToServer) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PB_CommandToServer) GetClientCallId() int64 {
	if m != nil {
		return m.ClientCallId
	}
	return 0
}

func (m *PB_CommandToServer) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *PB_CommandToServer) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PB_CommandToClient struct {
	ServerCallId int64  `protobuf:"varint,1,opt,name=ServerCallId" json:"ServerCallId,omitempty"`
	Command      string `protobuf:"bytes,2,opt,name=Command" json:"Command,omitempty"`
	Data         []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *PB_CommandToClient) Reset()                    { *m = PB_CommandToClient{} }
func (m *PB_CommandToClient) String() string            { return proto.CompactTextString(m) }
func (*PB_CommandToClient) ProtoMessage()               {}
func (*PB_CommandToClient) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PB_CommandToClient) GetServerCallId() int64 {
	if m != nil {
		return m.ServerCallId
	}
	return 0
}

func (m *PB_CommandToClient) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *PB_CommandToClient) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PB_CommandReceivedToServer struct {
	ClientCallId int64 `protobuf:"varint,1,opt,name=ClientCallId" json:"ClientCallId,omitempty"`
}

func (m *PB_CommandReceivedToServer) Reset()                    { *m = PB_CommandReceivedToServer{} }
func (m *PB_CommandReceivedToServer) String() string            { return proto.CompactTextString(m) }
func (*PB_CommandReceivedToServer) ProtoMessage()               {}
func (*PB_CommandReceivedToServer) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *PB_CommandReceivedToServer) GetClientCallId() int64 {
	if m != nil {
		return m.ClientCallId
	}
	return 0
}

type PB_CommandReceivedToClient struct {
	ServerCallId int64 `protobuf:"varint,1,opt,name=ServerCallId" json:"ServerCallId,omitempty"`
}

func (m *PB_CommandReceivedToClient) Reset()                    { *m = PB_CommandReceivedToClient{} }
func (m *PB_CommandReceivedToClient) String() string            { return proto.CompactTextString(m) }
func (*PB_CommandReceivedToClient) ProtoMessage()               {}
func (*PB_CommandReceivedToClient) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *PB_CommandReceivedToClient) GetServerCallId() int64 {
	if m != nil {
		return m.ServerCallId
	}
	return 0
}

type PB_UserWithMe struct {
	UserId         int32  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	UserName       string `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	FirstName      string `protobuf:"bytes,3,opt,name=FirstName" json:"FirstName,omitempty"`
	LastName       string `protobuf:"bytes,4,opt,name=LastName" json:"LastName,omitempty"`
	About          string `protobuf:"bytes,5,opt,name=About" json:"About,omitempty"`
	FullName       string `protobuf:"bytes,6,opt,name=FullName" json:"FullName,omitempty"`
	AvatarUrl      string `protobuf:"bytes,7,opt,name=AvatarUrl" json:"AvatarUrl,omitempty"`
	PrivacyProfile int32  `protobuf:"varint,8,opt,name=PrivacyProfile" json:"PrivacyProfile,omitempty"`
	Phone          string `protobuf:"bytes,9,opt,name=Phone" json:"Phone,omitempty"`
	UpdatedTime    int32  `protobuf:"varint,10,opt,name=UpdatedTime" json:"UpdatedTime,omitempty"`
	AppVersion     int32  `protobuf:"varint,11,opt,name=AppVersion" json:"AppVersion,omitempty"`
	FollowingType  int32  `protobuf:"varint,14,opt,name=FollowingType" json:"FollowingType,omitempty"`
}

func (m *PB_UserWithMe) Reset()                    { *m = PB_UserWithMe{} }
func (m *PB_UserWithMe) String() string            { return proto.CompactTextString(m) }
func (*PB_UserWithMe) ProtoMessage()               {}
func (*PB_UserWithMe) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *PB_UserWithMe) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_UserWithMe) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PB_UserWithMe) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PB_UserWithMe) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PB_UserWithMe) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *PB_UserWithMe) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *PB_UserWithMe) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *PB_UserWithMe) GetPrivacyProfile() int32 {
	if m != nil {
		return m.PrivacyProfile
	}
	return 0
}

func (m *PB_UserWithMe) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PB_UserWithMe) GetUpdatedTime() int32 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

func (m *PB_UserWithMe) GetAppVersion() int32 {
	if m != nil {
		return m.AppVersion
	}
	return 0
}

func (m *PB_UserWithMe) GetFollowingType() int32 {
	if m != nil {
		return m.FollowingType
	}
	return 0
}

type PB_Message struct {
	MessageKey         string      `protobuf:"bytes,1,opt,name=MessageKey" json:"MessageKey,omitempty"`
	RoomKey            string      `protobuf:"bytes,2,opt,name=RoomKey" json:"RoomKey,omitempty"`
	UserId             int64       `protobuf:"varint,3,opt,name=UserId" json:"UserId,omitempty"`
	PeerId             int64       `protobuf:"varint,20,opt,name=PeerId" json:"PeerId,omitempty"`
	RoomTypeId         int32       `protobuf:"varint,4,opt,name=RoomTypeId" json:"RoomTypeId,omitempty"`
	MessageTypeId      int32       `protobuf:"varint,5,opt,name=MessageTypeId" json:"MessageTypeId,omitempty"`
	Text               string      `protobuf:"bytes,6,opt,name=Text" json:"Text,omitempty"`
	ExtraJson          string      `protobuf:"bytes,7,opt,name=ExtraJson" json:"ExtraJson,omitempty"`
	IsByMe             int32       `protobuf:"varint,8,opt,name=IsByMe" json:"IsByMe,omitempty"`
	IsStared           int32       `protobuf:"varint,9,opt,name=IsStared" json:"IsStared,omitempty"`
	CreatedMs          int64       `protobuf:"varint,10,opt,name=CreatedMs" json:"CreatedMs,omitempty"`
	CreatedDeviceMs    int64       `protobuf:"varint,11,opt,name=CreatedDeviceMs" json:"CreatedDeviceMs,omitempty"`
	SortId             int64       `protobuf:"varint,12,opt,name=SortId" json:"SortId,omitempty"`
	PeerSeenTime       int64       `protobuf:"varint,13,opt,name=PeerSeenTime" json:"PeerSeenTime,omitempty"`
	ServerReceivedTime int64       `protobuf:"varint,14,opt,name=ServerReceivedTime" json:"ServerReceivedTime,omitempty"`
	ServerDeletedTime  int64       `protobuf:"varint,15,opt,name=ServerDeletedTime" json:"ServerDeletedTime,omitempty"`
	ISeenTime          int64       `protobuf:"varint,16,opt,name=ISeenTime" json:"ISeenTime,omitempty"`
	ToPush             int32       `protobuf:"varint,17,opt,name=ToPush" json:"ToPush,omitempty"`
	MsgFile_LocalSrc   string      `protobuf:"bytes,18,opt,name=MsgFile_LocalSrc,json=MsgFileLocalSrc" json:"MsgFile_LocalSrc,omitempty"`
	MsgFile_Status     int32       `protobuf:"varint,19,opt,name=MsgFile_Status,json=MsgFileStatus" json:"MsgFile_Status,omitempty"`
	File               *PB_MsgFile `protobuf:"bytes,100,opt,name=File" json:"File,omitempty"`
}

func (m *PB_Message) Reset()                    { *m = PB_Message{} }
func (m *PB_Message) String() string            { return proto.CompactTextString(m) }
func (*PB_Message) ProtoMessage()               {}
func (*PB_Message) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *PB_Message) GetMessageKey() string {
	if m != nil {
		return m.MessageKey
	}
	return ""
}

func (m *PB_Message) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *PB_Message) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PB_Message) GetPeerId() int64 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *PB_Message) GetRoomTypeId() int32 {
	if m != nil {
		return m.RoomTypeId
	}
	return 0
}

func (m *PB_Message) GetMessageTypeId() int32 {
	if m != nil {
		return m.MessageTypeId
	}
	return 0
}

func (m *PB_Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PB_Message) GetExtraJson() string {
	if m != nil {
		return m.ExtraJson
	}
	return ""
}

func (m *PB_Message) GetIsByMe() int32 {
	if m != nil {
		return m.IsByMe
	}
	return 0
}

func (m *PB_Message) GetIsStared() int32 {
	if m != nil {
		return m.IsStared
	}
	return 0
}

func (m *PB_Message) GetCreatedMs() int64 {
	if m != nil {
		return m.CreatedMs
	}
	return 0
}

func (m *PB_Message) GetCreatedDeviceMs() int64 {
	if m != nil {
		return m.CreatedDeviceMs
	}
	return 0
}

func (m *PB_Message) GetSortId() int64 {
	if m != nil {
		return m.SortId
	}
	return 0
}

func (m *PB_Message) GetPeerSeenTime() int64 {
	if m != nil {
		return m.PeerSeenTime
	}
	return 0
}

func (m *PB_Message) GetServerReceivedTime() int64 {
	if m != nil {
		return m.ServerReceivedTime
	}
	return 0
}

func (m *PB_Message) GetServerDeletedTime() int64 {
	if m != nil {
		return m.ServerDeletedTime
	}
	return 0
}

func (m *PB_Message) GetISeenTime() int64 {
	if m != nil {
		return m.ISeenTime
	}
	return 0
}

func (m *PB_Message) GetToPush() int32 {
	if m != nil {
		return m.ToPush
	}
	return 0
}

func (m *PB_Message) GetMsgFile_LocalSrc() string {
	if m != nil {
		return m.MsgFile_LocalSrc
	}
	return ""
}

func (m *PB_Message) GetMsgFile_Status() int32 {
	if m != nil {
		return m.MsgFile_Status
	}
	return 0
}

func (m *PB_Message) GetFile() *PB_MsgFile {
	if m != nil {
		return m.File
	}
	return nil
}

type PB_MsgFile struct {
	// general
	Name      string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Size      int64  `protobuf:"varint,2,opt,name=Size" json:"Size,omitempty"`
	FileType  int32  `protobuf:"varint,3,opt,name=FileType" json:"FileType,omitempty"`
	MimeType  string `protobuf:"bytes,4,opt,name=MimeType" json:"MimeType,omitempty"`
	Width     int32  `protobuf:"varint,5,opt,name=Width" json:"Width,omitempty"`
	Height    int32  `protobuf:"varint,6,opt,name=Height" json:"Height,omitempty"`
	Duration  int32  `protobuf:"varint,7,opt,name=Duration" json:"Duration,omitempty"`
	Extension string `protobuf:"bytes,8,opt,name=Extension" json:"Extension,omitempty"`
	ThumbData []byte `protobuf:"bytes,11,opt,name=ThumbData,proto3" json:"ThumbData,omitempty"`
	// just set in the client to server - data must be fetched sepratily for pushed msgs via ServerSrc
	Data []byte `protobuf:"bytes,10,opt,name=Data,proto3" json:"Data,omitempty"`
	// just set for push data
	ServerSrc string `protobuf:"bytes,101,opt,name=ServerSrc" json:"ServerSrc,omitempty"`
}

func (m *PB_MsgFile) Reset()                    { *m = PB_MsgFile{} }
func (m *PB_MsgFile) String() string            { return proto.CompactTextString(m) }
func (*PB_MsgFile) ProtoMessage()               {}
func (*PB_MsgFile) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *PB_MsgFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PB_MsgFile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PB_MsgFile) GetFileType() int32 {
	if m != nil {
		return m.FileType
	}
	return 0
}

func (m *PB_MsgFile) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *PB_MsgFile) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PB_MsgFile) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PB_MsgFile) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PB_MsgFile) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *PB_MsgFile) GetThumbData() []byte {
	if m != nil {
		return m.ThumbData
	}
	return nil
}

func (m *PB_MsgFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PB_MsgFile) GetServerSrc() string {
	if m != nil {
		return m.ServerSrc
	}
	return ""
}

type PB_Response struct {
	Status int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *PB_Response) Reset()                    { *m = PB_Response{} }
func (m *PB_Response) String() string            { return proto.CompactTextString(m) }
func (*PB_Response) ProtoMessage()               {}
func (*PB_Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *PB_Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PB_Request struct {
	Status int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *PB_Request) Reset()                    { *m = PB_Request{} }
func (m *PB_Request) String() string            { return proto.CompactTextString(m) }
func (*PB_Request) ProtoMessage()               {}
func (*PB_Request) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *PB_Request) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// //
type PB_RequestMsgAddMany struct {
	Request  *PB_Request   `protobuf:"bytes,1,opt,name=Request" json:"Request,omitempty"`
	Messages []*PB_Message `protobuf:"bytes,2,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *PB_RequestMsgAddMany) Reset()                    { *m = PB_RequestMsgAddMany{} }
func (m *PB_RequestMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_RequestMsgAddMany) ProtoMessage()               {}
func (*PB_RequestMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *PB_RequestMsgAddMany) GetRequest() *PB_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PB_RequestMsgAddMany) GetMessages() []*PB_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PB_ResponseMsgAddMany struct {
	Response *PB_Response `protobuf:"bytes,1,opt,name=Response" json:"Response,omitempty"`
}

func (m *PB_ResponseMsgAddMany) Reset()                    { *m = PB_ResponseMsgAddMany{} }
func (m *PB_ResponseMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_ResponseMsgAddMany) ProtoMessage()               {}
func (*PB_ResponseMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *PB_ResponseMsgAddMany) GetResponse() *PB_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

// ////////// Pushes ////////////
type PB_Push struct {
	Status int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *PB_Push) Reset()                    { *m = PB_Push{} }
func (m *PB_Push) String() string            { return proto.CompactTextString(m) }
func (*PB_Push) ProtoMessage()               {}
func (*PB_Push) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *PB_Push) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PB_Result struct {
	Status int32 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *PB_Result) Reset()                    { *m = PB_Result{} }
func (m *PB_Result) String() string            { return proto.CompactTextString(m) }
func (*PB_Result) ProtoMessage()               {}
func (*PB_Result) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *PB_Result) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// /
type PB_PushMsgAddMany struct {
	Push     *PB_Push         `protobuf:"bytes,1,opt,name=Push" json:"Push,omitempty"`
	Messages []*PB_Message    `protobuf:"bytes,2,rep,name=Messages" json:"Messages,omitempty"`
	Users    []*PB_UserWithMe `protobuf:"bytes,3,rep,name=Users" json:"Users,omitempty"`
}

func (m *PB_PushMsgAddMany) Reset()                    { *m = PB_PushMsgAddMany{} }
func (m *PB_PushMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_PushMsgAddMany) ProtoMessage()               {}
func (*PB_PushMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *PB_PushMsgAddMany) GetPush() *PB_Push {
	if m != nil {
		return m.Push
	}
	return nil
}

func (m *PB_PushMsgAddMany) GetMessages() []*PB_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PB_PushMsgAddMany) GetUsers() []*PB_UserWithMe {
	if m != nil {
		return m.Users
	}
	return nil
}

type PB_ResultMsgAddMany struct {
	Result *PB_Result `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *PB_ResultMsgAddMany) Reset()                    { *m = PB_ResultMsgAddMany{} }
func (m *PB_ResultMsgAddMany) String() string            { return proto.CompactTextString(m) }
func (*PB_ResultMsgAddMany) ProtoMessage()               {}
func (*PB_ResultMsgAddMany) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *PB_ResultMsgAddMany) GetResult() *PB_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type PB_MsgEvent struct {
	MessageKey string `protobuf:"bytes,1,opt,name=MessageKey" json:"MessageKey,omitempty"`
	RoomKey    string `protobuf:"bytes,2,opt,name=RoomKey" json:"RoomKey,omitempty"`
	PeerUserId int64  `protobuf:"varint,3,opt,name=PeerUserId" json:"PeerUserId,omitempty"`
	EventType  int32  `protobuf:"varint,4,opt,name=EventType" json:"EventType,omitempty"`
	AtTime     int64  `protobuf:"varint,10,opt,name=AtTime" json:"AtTime,omitempty"`
}

func (m *PB_MsgEvent) Reset()                    { *m = PB_MsgEvent{} }
func (m *PB_MsgEvent) String() string            { return proto.CompactTextString(m) }
func (*PB_MsgEvent) ProtoMessage()               {}
func (*PB_MsgEvent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *PB_MsgEvent) GetMessageKey() string {
	if m != nil {
		return m.MessageKey
	}
	return ""
}

func (m *PB_MsgEvent) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *PB_MsgEvent) GetPeerUserId() int64 {
	if m != nil {
		return m.PeerUserId
	}
	return 0
}

func (m *PB_MsgEvent) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *PB_MsgEvent) GetAtTime() int64 {
	if m != nil {
		return m.AtTime
	}
	return 0
}

type PB_PushMsgEvents struct {
	Push   *PB_Push       `protobuf:"bytes,1,opt,name=Push" json:"Push,omitempty"`
	Events []*PB_MsgEvent `protobuf:"bytes,2,rep,name=Events" json:"Events,omitempty"`
}

func (m *PB_PushMsgEvents) Reset()                    { *m = PB_PushMsgEvents{} }
func (m *PB_PushMsgEvents) String() string            { return proto.CompactTextString(m) }
func (*PB_PushMsgEvents) ProtoMessage()               {}
func (*PB_PushMsgEvents) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *PB_PushMsgEvents) GetPush() *PB_Push {
	if m != nil {
		return m.Push
	}
	return nil
}

func (m *PB_PushMsgEvents) GetEvents() []*PB_MsgEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type PB_ResultMsgEvents struct {
	Result *PB_Result `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *PB_ResultMsgEvents) Reset()                    { *m = PB_ResultMsgEvents{} }
func (m *PB_ResultMsgEvents) String() string            { return proto.CompactTextString(m) }
func (*PB_ResultMsgEvents) ProtoMessage()               {}
func (*PB_ResultMsgEvents) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *PB_ResultMsgEvents) GetResult() *PB_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_CommandToServer)(nil), "PB_CommandToServer")
	proto.RegisterType((*PB_CommandToClient)(nil), "PB_CommandToClient")
	proto.RegisterType((*PB_CommandReceivedToServer)(nil), "PB_CommandReceivedToServer")
	proto.RegisterType((*PB_CommandReceivedToClient)(nil), "PB_CommandReceivedToClient")
	proto.RegisterType((*PB_UserWithMe)(nil), "PB_UserWithMe")
	proto.RegisterType((*PB_Message)(nil), "PB_Message")
	proto.RegisterType((*PB_MsgFile)(nil), "PB_MsgFile")
	proto.RegisterType((*PB_Response)(nil), "PB_Response")
	proto.RegisterType((*PB_Request)(nil), "PB_Request")
	proto.RegisterType((*PB_RequestMsgAddMany)(nil), "PB_RequestMsgAddMany")
	proto.RegisterType((*PB_ResponseMsgAddMany)(nil), "PB_ResponseMsgAddMany")
	proto.RegisterType((*PB_Push)(nil), "PB_Push")
	proto.RegisterType((*PB_Result)(nil), "PB_Result")
	proto.RegisterType((*PB_PushMsgAddMany)(nil), "PB_PushMsgAddMany")
	proto.RegisterType((*PB_ResultMsgAddMany)(nil), "PB_ResultMsgAddMany")
	proto.RegisterType((*PB_MsgEvent)(nil), "PB_MsgEvent")
	proto.RegisterType((*PB_PushMsgEvents)(nil), "PB_PushMsgEvents")
	proto.RegisterType((*PB_ResultMsgEvents)(nil), "PB_ResultMsgEvents")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *PB_Message, opts ...grpc.CallOption) (*PB_UserWithMe, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *PB_Message, opts ...grpc.CallOption) (*PB_UserWithMe, error) {
	out := new(PB_UserWithMe)
	err := grpc.Invoke(ctx, "/Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *PB_Message) (*PB_UserWithMe, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PB_Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*PB_Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_global.proto",
}

func init() { proto.RegisterFile("pb_global.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1047 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0x26, 0x75, 0x9d, 0xa6, 0x93, 0x5e, 0xda, 0xee, 0xf5, 0x4e, 0x56, 0x75, 0x3a, 0x82, 0x69,
	0x21, 0x27, 0x21, 0x3f, 0x1c, 0x3c, 0xc0, 0x1b, 0x49, 0x7b, 0xa5, 0x81, 0x33, 0xb2, 0x36, 0xe9,
	0x9d, 0xc4, 0x4b, 0xe4, 0xc4, 0xdb, 0xc4, 0x92, 0x63, 0x07, 0xaf, 0x13, 0x1a, 0x9e, 0xf8, 0x23,
	0xbc, 0xf1, 0xca, 0xaf, 0xe3, 0x0f, 0xa0, 0x99, 0x5d, 0x6f, 0x9c, 0x42, 0x45, 0x8f, 0x37, 0x7f,
	0xdf, 0xcc, 0xee, 0xcc, 0xce, 0x37, 0x33, 0x09, 0x1c, 0x2e, 0xc6, 0xa3, 0x69, 0x92, 0x8d, 0xc3,
	0xc4, 0x5b, 0xe4, 0x59, 0x91, 0xb9, 0xb7, 0xc0, 0x82, 0xde, 0xe8, 0x22, 0x9b, 0xcf, 0xc3, 0x34,
	0x1a, 0x66, 0x03, 0x91, 0xaf, 0x44, 0xce, 0x5c, 0x38, 0xb8, 0x48, 0x62, 0x91, 0x16, 0x17, 0x61,
	0x92, 0xf4, 0x23, 0xa7, 0xd6, 0xae, 0x75, 0x2c, 0xbe, 0xc5, 0x31, 0x07, 0xf6, 0xf4, 0x31, 0x67,
	0xa7, 0x5d, 0xeb, 0xec, 0xf3, 0x12, 0x32, 0x06, 0xbb, 0x97, 0x61, 0x11, 0x3a, 0x56, 0xbb, 0xd6,
	0x39, 0xe0, 0xf4, 0x7d, 0x3f, 0x8e, 0xba, 0x09, 0xe3, 0xa8, 0x88, 0xdb, 0x71, 0xaa, 0xdc, 0x07,
	0xc6, 0xf9, 0x16, 0x4e, 0x37, 0x71, 0xb8, 0x98, 0x88, 0x78, 0x25, 0x3e, 0xe8, 0x5d, 0x0f, 0xdd,
	0xf0, 0xf8, 0x8c, 0xdd, 0xbf, 0x76, 0xe0, 0x49, 0xd0, 0x1b, 0xdd, 0x48, 0x91, 0xbf, 0x8f, 0x8b,
	0x99, 0x2f, 0xd8, 0x73, 0xa8, 0x23, 0xd2, 0xfe, 0x36, 0xd7, 0x88, 0x9d, 0x42, 0x03, 0xbf, 0x7e,
	0x0c, 0xe7, 0x42, 0x3f, 0xce, 0x60, 0xf6, 0x02, 0xf6, 0xaf, 0xe2, 0x5c, 0x16, 0x64, 0xb4, 0xc8,
	0xb8, 0x21, 0xf0, 0xe4, 0xdb, 0x50, 0x1b, 0x77, 0xd5, 0xc9, 0x12, 0xb3, 0x13, 0xb0, 0xbb, 0xe3,
	0x6c, 0x59, 0x38, 0x36, 0x19, 0x14, 0xc0, 0x13, 0x57, 0xcb, 0x24, 0xa1, 0x13, 0x75, 0x75, 0xa2,
	0xc4, 0x18, 0xab, 0xbb, 0x0a, 0x8b, 0x30, 0xbf, 0xc9, 0x13, 0x67, 0x4f, 0xc5, 0x32, 0x04, 0xfb,
	0x0c, 0x5a, 0x41, 0x1e, 0xaf, 0xc2, 0xc9, 0x3a, 0xc8, 0xb3, 0xdb, 0x38, 0x11, 0x4e, 0x83, 0x5e,
	0x71, 0x8f, 0xc5, 0xb8, 0xc1, 0x2c, 0x4b, 0x85, 0xb3, 0xaf, 0xe2, 0x12, 0x60, 0x6d, 0x68, 0xde,
	0x2c, 0xa2, 0xb0, 0x10, 0xd1, 0x30, 0x9e, 0x0b, 0x07, 0xe8, 0x68, 0x95, 0x62, 0x2f, 0x01, 0xba,
	0x8b, 0xc5, 0x3b, 0x91, 0xcb, 0x38, 0x4b, 0x9d, 0x26, 0x39, 0x54, 0x18, 0x76, 0x06, 0x4f, 0xae,
	0xb2, 0x24, 0xc9, 0x7e, 0x89, 0xd3, 0xe9, 0x70, 0xbd, 0x10, 0x4e, 0x8b, 0x5c, 0xb6, 0x49, 0xf7,
	0x4f, 0x1b, 0x20, 0xe8, 0x8d, 0x7c, 0x21, 0x65, 0x38, 0xa5, 0x4b, 0xf5, 0xe7, 0x0f, 0x62, 0x4d,
	0x65, 0xdf, 0xe7, 0x15, 0x06, 0xdb, 0x8a, 0x67, 0xd9, 0x1c, 0x8d, 0xba, 0xad, 0x34, 0xac, 0x88,
	0x65, 0x91, 0xb8, 0xa5, 0x58, 0xcf, 0xa1, 0x1e, 0x08, 0xe2, 0x4f, 0x14, 0xaf, 0x10, 0x46, 0xc2,
	0xa3, 0x98, 0x44, 0x3f, 0x22, 0x31, 0x6c, 0x5e, 0x61, 0x30, 0x7d, 0x1d, 0x57, 0xbb, 0xd8, 0x2a,
	0xfd, 0x2d, 0x12, 0x9b, 0x79, 0x28, 0xee, 0x0a, 0x2d, 0x0d, 0x7d, 0xa3, 0x2c, 0x6f, 0xee, 0x8a,
	0x3c, 0xfc, 0x5e, 0x66, 0x69, 0x29, 0x8b, 0x21, 0x30, 0x9f, 0xbe, 0xec, 0xad, 0xfd, 0x52, 0x0e,
	0x8d, 0x50, 0xe8, 0xbe, 0x1c, 0x14, 0x61, 0x2e, 0x22, 0x52, 0xc2, 0xe6, 0x06, 0xe3, 0x8d, 0x17,
	0xb9, 0xc0, 0xca, 0xfb, 0x92, 0xa4, 0xb0, 0xf8, 0x86, 0x60, 0x1d, 0x38, 0xd4, 0xe0, 0x52, 0xac,
	0xe2, 0x89, 0xf0, 0x25, 0xa9, 0x61, 0xf1, 0xfb, 0x34, 0xc6, 0x1e, 0x64, 0x79, 0xd1, 0x8f, 0x9c,
	0x03, 0x55, 0x0b, 0x85, 0x70, 0x3c, 0xb0, 0x2a, 0x03, 0x21, 0x52, 0x52, 0xfb, 0x89, 0x1a, 0x8f,
	0x2a, 0xc7, 0x3c, 0x60, 0x6a, 0x5c, 0xcc, 0x70, 0xa1, 0x67, 0x8b, 0x3c, 0xff, 0xc5, 0xc2, 0xbe,
	0x80, 0x63, 0xc5, 0x5e, 0x8a, 0x44, 0x94, 0x6d, 0x74, 0x48, 0xee, 0xff, 0x34, 0xe0, 0x0b, 0xfb,
	0x26, 0xfc, 0x91, 0x7a, 0xa1, 0x21, 0x30, 0xef, 0x61, 0x16, 0x2c, 0xe5, 0xcc, 0x39, 0x56, 0x35,
	0x53, 0x88, 0xbd, 0x82, 0x23, 0x5f, 0x4e, 0xaf, 0xe2, 0x44, 0x8c, 0xde, 0x66, 0x93, 0x30, 0x19,
	0xe4, 0x13, 0x87, 0x51, 0xc1, 0x0f, 0x35, 0x5f, 0xd2, 0xec, 0x1c, 0x5a, 0xa5, 0xeb, 0xa0, 0x08,
	0x8b, 0xa5, 0x74, 0x9e, 0x6a, 0x3d, 0x15, 0xab, 0x48, 0xf6, 0x31, 0xec, 0x22, 0x72, 0xa2, 0x76,
	0xad, 0xd3, 0x7c, 0xdd, 0xf4, 0xb0, 0x35, 0x95, 0x03, 0x27, 0x83, 0xfb, 0xc7, 0x8e, 0xea, 0x57,
	0x45, 0xa2, 0xfe, 0x34, 0x9a, 0xaa, 0x53, 0xe9, 0x1b, 0xb9, 0x41, 0xfc, 0xab, 0x5a, 0x0d, 0x16,
	0xa7, 0x6f, 0x1a, 0xe3, 0x38, 0xa1, 0xae, 0xa1, 0xfe, 0xb4, 0xb9, 0xc1, 0x68, 0xf3, 0xe3, 0xb9,
	0xb2, 0xe9, 0xa5, 0x50, 0x62, 0x1c, 0xce, 0xf7, 0x71, 0x54, 0xcc, 0x74, 0xf7, 0x29, 0x80, 0xf5,
	0xb8, 0x16, 0xf1, 0x74, 0xa6, 0xfa, 0xce, 0xe6, 0x1a, 0xe1, 0x4d, 0x97, 0xcb, 0x3c, 0x2c, 0x62,
	0xdd, 0x78, 0x36, 0x37, 0x58, 0x77, 0xa5, 0x48, 0x69, 0x5a, 0x1b, 0xa6, 0x2b, 0x15, 0x81, 0xd6,
	0xe1, 0x6c, 0x39, 0x1f, 0xd3, 0x66, 0x6e, 0xd2, 0x66, 0xde, 0x10, 0x66, 0x65, 0xc3, 0x66, 0x65,
	0xe3, 0x09, 0x25, 0x23, 0x16, 0x5d, 0xa8, 0xfb, 0x0c, 0xe1, 0x9e, 0x43, 0x33, 0xe8, 0x8d, 0xb8,
	0x90, 0x8b, 0x2c, 0x95, 0x24, 0xa0, 0xae, 0xba, 0xde, 0xa4, 0x0a, 0xb9, 0x67, 0x54, 0x4c, 0x2e,
	0x7e, 0x5e, 0x0a, 0x59, 0x3c, 0xe8, 0x75, 0x0b, 0x27, 0x1b, 0x2f, 0x5f, 0x4e, 0xbb, 0x51, 0xe4,
	0x87, 0xe9, 0x9a, 0x9d, 0xc3, 0x9e, 0x26, 0xe9, 0x80, 0xd6, 0x4b, 0x53, 0xbc, 0xb4, 0xb1, 0xcf,
	0xa1, 0xa1, 0x87, 0x56, 0x3a, 0x3b, 0x6d, 0xcb, 0xe8, 0xaa, 0x38, 0x6e, 0x8c, 0x6e, 0x17, 0x9e,
	0x55, 0x92, 0xae, 0x04, 0xea, 0x40, 0xa3, 0x64, 0x75, 0xa4, 0x03, 0xaf, 0xe2, 0xc9, 0x8d, 0xd5,
	0xfd, 0x04, 0xf6, 0x82, 0xde, 0x88, 0x9a, 0xf3, 0xa1, 0xd7, 0x7c, 0x0a, 0xfb, 0xea, 0xec, 0x32,
	0x79, 0xf8, 0xc9, 0xbf, 0xd5, 0xe0, 0x58, 0x5f, 0x54, 0xc9, 0xe3, 0x05, 0xec, 0xd2, 0x14, 0xa8,
	0x1c, 0x1a, 0x9e, 0xf6, 0xe0, 0xc4, 0x3e, 0xfa, 0x9d, 0xec, 0x0c, 0x6c, 0x5c, 0x8e, 0xd2, 0xb1,
	0xc8, 0xab, 0xe5, 0x6d, 0xfd, 0xec, 0x71, 0x65, 0x74, 0xbf, 0x81, 0xa7, 0x26, 0xcf, 0x4a, 0x0e,
	0x2e, 0xd4, 0x15, 0xa7, 0xb3, 0x00, 0xcf, 0x78, 0x71, 0x6d, 0x71, 0x7f, 0xaf, 0x91, 0xfc, 0xbe,
	0x9c, 0xbe, 0x59, 0xe1, 0xcf, 0xef, 0xff, 0xdf, 0xea, 0x2f, 0x01, 0x70, 0x0b, 0x6d, 0x6d, 0xf6,
	0x0a, 0x43, 0x5d, 0x8d, 0x21, 0xcc, 0xf0, 0xd8, 0x7c, 0x43, 0x60, 0x75, 0xbb, 0x85, 0xf9, 0xfd,
	0xb2, 0xb8, 0x46, 0xee, 0x3b, 0x38, 0xda, 0x14, 0x97, 0xdc, 0xe5, 0x7f, 0xd4, 0xf6, 0x0c, 0xea,
	0xca, 0x4f, 0x57, 0xf6, 0xc0, 0xab, 0xbc, 0x8f, 0x6b, 0x9b, 0xfb, 0x35, 0xfd, 0x5d, 0x32, 0x25,
	0xd3, 0x37, 0x3f, 0xa2, 0x62, 0xaf, 0xbf, 0x82, 0xbd, 0xef, 0x72, 0x21, 0x0a, 0x91, 0xb3, 0x57,
	0xd0, 0x18, 0x84, 0xeb, 0x6b, 0x91, 0x24, 0x19, 0xab, 0x0a, 0x78, 0x7a, 0x4f, 0x27, 0xf7, 0xa3,
	0xde, 0x33, 0x68, 0xc4, 0xb9, 0x37, 0x97, 0xde, 0x62, 0xdc, 0xdb, 0x09, 0x7a, 0xd7, 0x56, 0x50,
	0xfb, 0xa9, 0x76, 0x37, 0xae, 0xd3, 0x9f, 0xc4, 0x2f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd6,
	0xe8, 0x3e, 0xba, 0x37, 0x0a, 0x00, 0x00,
}
